In [20]:
# For tips on running notebooks in Google Colab, see
# https://docs.pytorch.org/tutorials/beginner/colab
%matplotlib inline

DEEP LEARNING -- ASSIGNMENT 1
===

*Purpose of this assignment is to predict the ´charges´ column of the insurance.csv file through a Neural Network model.

Optuna, Optimizers, (???)

CONTENT INDEX

0. DATA LOADING

1. DATA PREPARATION AND UNDERSTANDING
- 1.1 FEATURE ENGENEERING
- 1.2 PREPROCESSING
- 1.3 DATA SPLITTING (TRAIN/TEST)

2. NEURAL NETWORK DESIGN (SHALLOW NN)
- 2.1 LAYERS AND UNITS
- 2.2 ACTIVATION FUNCTIONS

3. TRAINING METHODOLOGY
- 3.1 LOSS FUNCTION
- 3.2 OPTIMIZER
- 3.3 INITIALIZATION

4. MODEL TRAINING

5. PERFORMANCE EVALUATION

In [21]:
#NECESSARY IMPORTS
import numpy as np
import pandas as pd
 
import torch
import torch.nn as nn
import torch.nn.init as init
 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import optuna

In [22]:
# SEED FOR REPRODUCIBILITY
# so we get the same results every time we run the notebook
SEED = 42

# !!!
# Set the random seed for both PyTorch and NumPy to ensure reproducibility of results.
torch.manual_seed(SEED)
np.random.seed(SEED)

# Check if an NVIDIA GPU (CUDA) is available. 
# If yes, we use 'cuda'; otherwise, we fall back to the 'cpu'.
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Print the device choice so we know if the code is running on the GPU or CPU
print(f"Using device: {DEVICE}\n")

Using device: cpu

1. DATA PREPARATION AND UNDERSTANDING
---

In [23]:
# 0. DATASET LOADING
df = pd.read_csv("insurance.csv")
df.head()

#TODO: Check the dataset for any issues (missing values, data types, etc.) and preprocess as needed.
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [24]:
# 1.1 FEATURE ENGENEERING
# We use get_dummies to transform the 'region' column into multiple numeric columns.
# If 'region' has 4 categories (NE, NW, SE, SW), it will create 4 columns.
# 'drop_first=True' is used to avoid the "Dummy Variable Trap":
# It removes one column (e.g., 'region_northeast'). 
# If the remaining columns (NW, SE, SW) are all 0, the model knows the region MUST be NE.
# This prevents mathematical redundancy (multicollinearity) in your model.
data = pd.get_dummies(df, columns=['region'], drop_first=True)
# We manually map the strings to integers: Female becomes 0, Male becomes 1.
data['sex'] = data['sex'].map({'female': 0, 'male': 1})
# 'Binary Encoding' for smoking status:
# 'no' becomes 0 and 'yes' becomes 1.
data['smoker'] = data['smoker'].map({'no': 0, 'yes': 1})
# Display the first 5 rows of the new DataFrame to verify the changes.
data.head()

,age,sex,bmi,children,smoker,charges,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,16884.92400,False,False,True
1,18,1,33.770,1,0,1725.55230,False,True,False
2,28,1,33.000,3,0,4449.46200,False,True,False
3,33,1,22.705,0,0,21984.47061,True,False,False
4,32,1,28.880,0,0,3866.85520,True,False,False

In [25]:
# 1.2 PREPROCESSING (NORMALIZATION, STANDARDIZATION, ETC.)
# Define which numeric columns need to be scaled. It is not necessary to scale the one-hot encoded 'region' columns because they are already in a 0/1 format.
# We include 'charges' here because it's our target variable and we want it on a similar scale as the features.
cols_a_escalar = ['age', 'bmi', 'children', 'charges']

# Initialize the StandardScaler.
# This follows the formula: z = (x - mean) / standard_deviation
# It centers the data around 0 with a standard deviation of 1.
scaler = StandardScaler()

# fit_transform does two things:
# 1. 'fit' calculates the average (mean) and variance of each column.
# 2. 'transform' actually applies the math to change the numbers.
data[cols_a_escalar] = scaler.fit_transform(data[cols_a_escalar])
# Ensure all data in the DataFrame is a float (decimal number).
# This prevents errors during PyTorch tensor conversion later.
data = data.astype(float)

# X = every column except 'charges' (independent variable)
X = data.drop(columns=['charges'])
# y = only the column 'charges' (dependent variable, what we want to predict)
y = data['charges']

data.head()

,age,sex,bmi,children,smoker,charges,region_northwest,region_southeast,region_southwest
0,-1.438764,0.0,-0.453320,-0.908614,1.0,0.298584,0.0,0.0,1.0
1,-1.509965,1.0,0.509621,-0.078767,0.0,-0.953689,0.0,1.0,0.0
2,-0.797954,1.0,0.383307,1.580926,0.0,-0.728675,0.0,1.0,0.0
3,-0.441948,1.0,-1.305531,-0.908614,0.0,0.719843,1.0,0.0,0.0
4,-0.513149,1.0,-0.292556,-0.908614,0.0,-0.776802,1.0,0.0,0.0

In [26]:
# 1.3 DATA SPLITTING (TRAIN/VAL/TEST)

# We split the data: 80% for training and 20% for testing.
# random_state=42 ensures the "random" split is the same every time you run the code.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# We print the number of rows in each set 
print(f"Muestras de entrenamiento: {len(X_train)}")
print(f"Muestras de prueba: {len(X_test)}")

Muestras de entrenamiento: 1070
Muestras de prueba: 268

2. NEURAL NETWORK DESIGN (Deep, Shallow...?)
---

In [34]:
# 2.2 ACTIVATION FUNCTIONS
# Instanciamos el modelo definiendo las activaciones dentro
class InsuranceModel(nn.Module):
    def __init__(self, input_dim):
        super(InsuranceModel, self).__init__() # initializes the pytorch functionality for our model
        # defines the path of the data through the layers and activations in a single sequential block.
        self.net = nn.Sequential(
            # First layer: Multiplies the input features by weights and adds a bias to produce 64 new features.
            nn.Linear(input_dim, 64),
            # Applies the ReLU activation function to introduce non-linearity.
            nn.ReLU(),             
            # Second layer: Takes the 64 features from the first layer and transforms them into 32 new features.
            nn.Linear(64, 32),
            # Second ReLU activation to add non-linearity after the second layer.
            nn.ReLU(),   
            # Output layer: Takes the 32 features from the second layer and produces a single output (the predicted insurance cost).  
            # No activation function here because it's a regression problem; we want the output to be able to take any value, not just positive integers.         
            nn.Linear(32, 1)    
        )
        
    def forward(self, x):
        # The forward method defines how the input data flows through the network.
        return self.net(x)

#IMPLEMENTATION OF OPTUNA
class OptunaInsuranceModel(nn.Module):
    def __init__(self, input_dim, hidden_layers):
        super(OptunaInsuranceModel, self).__init__()
        layers = []
        in_features = input_dim
        
        # Build the hidden layers based on Optuna's suggestion
        for h_size in hidden_layers:
            layers.append(nn.Linear(in_features, h_size))
            layers.append(nn.ReLU())
            in_features = h_size
            
        # Final output layer
        layers.append(nn.Linear(in_features, 1))
        self.net = nn.Sequential(*layers)
        
    def forward(self, x):
        return self.net(x)

3. TRAINING METHODOLOGY
---

In [28]:
# 3.1 TENSOR INITIALIZATION
# AFTER splitting and scaling
X_train_t = torch.tensor(X_train.to_numpy(), dtype=torch.float32)
y_train_t = torch.tensor(y_train.to_numpy(), dtype=torch.float32).view(-1, 1)

X_test_t = torch.tensor(X_test.to_numpy(), dtype=torch.float32)
y_test_t = torch.tensor(y_test.to_numpy(), dtype=torch.float32).view(-1, 1)

In [29]:
# 3.1 LOSS FUNCTION (Regression --> MSE?)
criterion = nn.MSELoss()

In [30]:
# 3.2 INITIALIZATION (He Initialization)

# Obtains the number of input features from X_train (the number of columns) to initialize the model correctly.
input_size = X_train.shape[1]
# We create an instance of the InsuranceModel class, passing the number of input features as an argument.
model = InsuranceModel(input_size)

# He initialization (also known as Kaiming initialization) is a method for initializing the weights of neural networks, 
# especially those using ReLU activations.
def init_weights(m):
    # We check if the layer 'm' is an instance of nn.Linear, which means it's a fully connected layer.
    # We don't want to initialize activation functions or other types of layers,
    # only the linear layers that have weights and biases.
    if isinstance(m, nn.Linear):
        # We use Kaiming normal initialization for the weights of the layer 'm'.
        init.kaiming_normal_(m.weight, nonlinearity='relu')
        # We set the bias of the layer 'm' to a small constant value (0.01) to ensure that the 
        # neurons are active at the beginning of training.
        m.bias.data.fill_(0.01)

# Aplicarlo a tu modelo
model.apply(init_weights)   

print(model)

InsuranceModel(
  (net): Sequential(
    (0): Linear(in_features=8, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=32, bias=True)
    (3): ReLU()
    (4): Linear(in_features=32, out_features=1, bias=True)
  )
)

In [31]:
# 3.3 OPTIMIZER (SGD, ADAM, ..., ?)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001) # lr=1e-3 or lr=0.001?

4. MODEL TRAINING
---

In [32]:
def train(model, optimizer, epochs=100):
    for epoch in range(epochs):
        model.train()
        
        optimizer.zero_grad()        # clear old gradients first
        preds = model(X_train_t)
        loss = criterion(preds, y_train_t)
        loss.backward()
        optimizer.step()

        if epoch % 10 == 0:
            print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

train(model, optimizer, epochs=100)

Epoch 0, Loss: 1.3592
Epoch 10, Loss: 0.8412
Epoch 20, Loss: 0.5570
Epoch 30, Loss: 0.4025
Epoch 40, Loss: 0.3140
Epoch 50, Loss: 0.2580
Epoch 60, Loss: 0.2204
Epoch 70, Loss: 0.1970
Epoch 80, Loss: 0.1825
Epoch 90, Loss: 0.1725

5. PERFORMANCE EVALUATION
---

In [33]:
model.eval()
with torch.no_grad():
    preds = model(X_test_t).numpy()

rmse = np.sqrt(mean_squared_error(y_test, preds))
mae = mean_absolute_error(y_test, preds)
r2 = r2_score(y_test, preds)

print(f"RMSE: {rmse:.2f}")
print(f"MAE: {mae:.2f}")
print(f"R2: {r2:.3f}")

RMSE: 0.41
MAE: 0.29
R2: 0.842

In [ ]:
# 3.4 HYPERPARAMETER TUNING WITH OPTUNA
def objective(trial):
    # 1. SUGGEST NUMBER OF LAYERS (e.g., between 1 and 3)
    n_layers = trial.suggest_int("n_layers", 1, 3)
    
    hidden_layers = []
    for i in range(n_layers):
        # Suggest neurons for each layer (e.g., layer_0, layer_1...)
        size = trial.suggest_int(f"n_units_l{i}", 16, 128, step=16)
        hidden_layers.append(size)
    
    lr = trial.suggest_float("lr", 1e-4, 1e-2, log=True)

    # 2. BUILD AND TRAIN
    model = OptunaInsuranceModel(X_train.shape[1], hidden_layers).to(DEVICE)
    model.apply(init_weights)
    
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.MSELoss()

    for epoch in range(200):
        model.train()
        optimizer.zero_grad()
        preds = model(X_train_t.to(DEVICE))
        loss = criterion(preds, y_train_t.to(DEVICE))
        loss.backward()
        optimizer.step()

    # 3. EVALUATE
    model.eval()
    with torch.no_grad():
        test_preds = model(X_test_t.to(DEVICE))
        score = r2_score(y_test_t.cpu(), test_preds.cpu())
        
    return score

# Creamos el estudio
study = optuna.create_study(direction="maximize") 

# Ejecutamos 30 o 50 intentos para tener datos suficientes
study.optimize(objective, n_trials=500)

# 1. Obtener el mejor R2 (el valor más alto)
mejor_r2 = study.best_value

# 2. Obtener los parámetros exactos que lograron ese R2
mejores_params = study.best_params

print("="*30)
print(f"EL MEJOR VALOR DIRECTO: {mejor_r2:.4f}")
print("="*30)
print("Configuración ganadora:")
for parametro, valor in mejores_params.items():
    print(f" -> {parametro}: {valor}")

[I 2026-03-24 13:02:21,177] A new study created in memory with name: no-name-888ae83b-af39-4748-8406-ad6a76dc514a
[I 2026-03-24 13:02:21,329] Trial 0 finished with value: 0.8713605999946594 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.0031805648380591528}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:21,684] Trial 1 finished with value: 0.8474063277244568 and parameters: {'n_layers': 2, 'n_units_l0': 128, 'n_units_l1': 96, 'lr': 0.0028464856503854375}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:22,025] Trial 2 finished with value: 0.8535853624343872 and parameters: {'n_layers': 3, 'n_units_l0': 80, 'n_units_l1': 16, 'n_units_l2': 80, 'lr': 0.0014899819590508728}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:22,328] Trial 3 finished with value: 0.8378257751464844 and parameters: {'n_layers': 3, 'n_units_l0': 64, 'n_units_l1': 64, 'n_units_l2': 16, 'lr': 0.000497238152637261}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:22,623] Trial 4 finished with value: 0.8546533584594727 and parameters: {'n_layers': 3, 'n_units_l0': 80, 'n_units_l1': 16, 'n_units_l2': 96, 'lr': 0.0006620070088722578}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:22,906] Trial 5 finished with value: 0.8446222543716431 and parameters: {'n_layers': 2, 'n_units_l0': 80, 'n_units_l1': 96, 'lr': 0.0005117109304415892}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:23,203] Trial 6 finished with value: 0.5318911671638489 and parameters: {'n_layers': 2, 'n_units_l0': 96, 'n_units_l1': 64, 'lr': 0.0001053259321248024}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:23,427] Trial 7 finished with value: 0.8402152061462402 and parameters: {'n_layers': 2, 'n_units_l0': 64, 'n_units_l1': 96, 'lr': 0.00023908376849950545}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:23,571] Trial 8 finished with value: 0.8657290935516357 and parameters: {'n_layers': 2, 'n_units_l0': 16, 'n_units_l1': 32, 'lr': 0.005008063456418317}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:23,702] Trial 9 finished with value: 0.8566311597824097 and parameters: {'n_layers': 1, 'n_units_l0': 16, 'lr': 0.006803973816308017}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:23,850] Trial 10 finished with value: 0.8098525404930115 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.001746315848292701}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:24,014] Trial 11 finished with value: 0.8611416220664978 and parameters: {'n_layers': 1, 'n_units_l0': 16, 'lr': 0.009228418434250759}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:24,167] Trial 12 finished with value: 0.8451040983200073 and parameters: {'n_layers': 1, 'n_units_l0': 32, 'lr': 0.00405582824178709}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:24,297] Trial 13 finished with value: 0.8668346405029297 and parameters: {'n_layers': 1, 'n_units_l0': 32, 'lr': 0.0044471497183221865}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:24,430] Trial 14 finished with value: 0.8677012920379639 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.0025889203332457055}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:24,591] Trial 15 finished with value: 0.8472089171409607 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.0022018969971335854}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:23,976] Trial 16 finished with value: 0.7846633791923523 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.001105324276649496}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:24,120] Trial 17 finished with value: 0.8662502765655518 and parameters: {'n_layers': 1, 'n_units_l0': 128, 'lr': 0.0029108997865824387}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:24,275] Trial 18 finished with value: 0.8554680347442627 and parameters: {'n_layers': 1, 'n_units_l0': 96, 'lr': 0.0010570032609033533}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:24,493] Trial 19 finished with value: 0.8252447843551636 and parameters: {'n_layers': 2, 'n_units_l0': 32, 'n_units_l1': 128, 'lr': 0.009012453338236408}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:24,754] Trial 20 finished with value: 0.8462897539138794 and parameters: {'n_layers': 2, 'n_units_l0': 64, 'n_units_l1': 128, 'lr': 0.0035127930767286496}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:24,902] Trial 21 finished with value: 0.8682736754417419 and parameters: {'n_layers': 1, 'n_units_l0': 32, 'lr': 0.005773361609612968}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:25,048] Trial 22 finished with value: 0.858070969581604 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.005862148581766034}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:25,184] Trial 23 finished with value: 0.838480532169342 and parameters: {'n_layers': 1, 'n_units_l0': 32, 'lr': 0.0020576869732165043}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:25,338] Trial 24 finished with value: 0.8659912347793579 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.006431476292157655}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:25,473] Trial 25 finished with value: 0.8381757736206055 and parameters: {'n_layers': 1, 'n_units_l0': 32, 'lr': 0.002740519107782173}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:25,649] Trial 26 finished with value: 0.8566439747810364 and parameters: {'n_layers': 1, 'n_units_l0': 64, 'lr': 0.001581235763970121}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:25,855] Trial 27 finished with value: 0.8595027327537537 and parameters: {'n_layers': 2, 'n_units_l0': 16, 'n_units_l1': 48, 'lr': 0.0038481411823168793}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:25,994] Trial 28 finished with value: 0.8687470555305481 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.007361107270435187}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:26,286] Trial 29 finished with value: 0.8496767282485962 and parameters: {'n_layers': 2, 'n_units_l0': 96, 'n_units_l1': 112, 'lr': 0.007637889244813142}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:26,428] Trial 30 finished with value: 0.8588754534721375 and parameters: {'n_layers': 1, 'n_units_l0': 112, 'lr': 0.005157991583254439}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:26,575] Trial 31 finished with value: 0.8577033877372742 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.0029493731528284603}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:26,720] Trial 32 finished with value: 0.8642733097076416 and parameters: {'n_layers': 1, 'n_units_l0': 32, 'lr': 0.002737908463528799}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:26,906] Trial 33 finished with value: 0.8568564653396606 and parameters: {'n_layers': 1, 'n_units_l0': 64, 'lr': 0.009427456104301825}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:27,039] Trial 34 finished with value: 0.752727746963501 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.0013090285468942725}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:27,420] Trial 35 finished with value: 0.8411827087402344 and parameters: {'n_layers': 3, 'n_units_l0': 80, 'n_units_l1': 80, 'n_units_l2': 128, 'lr': 0.0007753320567443144}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:27,607] Trial 36 finished with value: 0.8680329322814941 and parameters: {'n_layers': 1, 'n_units_l0': 64, 'lr': 0.005575705483936885}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:28,045] Trial 37 finished with value: 0.8067540526390076 and parameters: {'n_layers': 3, 'n_units_l0': 64, 'n_units_l1': 48, 'n_units_l2': 16, 'lr': 0.007434417591389166}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:28,316] Trial 38 finished with value: 0.8356567621231079 and parameters: {'n_layers': 2, 'n_units_l0': 80, 'n_units_l1': 48, 'lr': 0.0003730874857728811}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:28,597] Trial 39 finished with value: 0.8623571991920471 and parameters: {'n_layers': 2, 'n_units_l0': 64, 'n_units_l1': 80, 'lr': 0.005843026465598852}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:28,748] Trial 40 finished with value: -0.21742427349090576 and parameters: {'n_layers': 1, 'n_units_l0': 32, 'lr': 0.00013356987383628073}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:28,919] Trial 41 finished with value: 0.8682985901832581 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.0048733558811829055}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:29,055] Trial 42 finished with value: 0.8615617752075195 and parameters: {'n_layers': 1, 'n_units_l0': 64, 'lr': 0.00458325457979708}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:29,248] Trial 43 finished with value: 0.8702521324157715 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.007414547281373969}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:29,402] Trial 44 finished with value: 0.8669079542160034 and parameters: {'n_layers': 1, 'n_units_l0': 16, 'lr': 0.007394128960435316}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:29,569] Trial 45 finished with value: 0.862306535243988 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.003610672213510307}. Best is trial 0 with value: 0.8713605999946594.
[I 2026-03-24 13:02:29,734] Trial 46 finished with value: 0.8720903396606445 and parameters: {'n_layers': 1, 'n_units_l0': 32, 'lr': 0.009857990143307897}. Best is trial 46 with value: 0.8720903396606445.
[I 2026-03-24 13:02:29,893] Trial 47 finished with value: 0.8605348467826843 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.009796865472975574}. Best is trial 46 with value: 0.8720903396606445.
[I 2026-03-24 13:02:30,121] Trial 48 finished with value: 0.8608236312866211 and parameters: {'n_layers': 2, 'n_units_l0': 32, 'n_units_l1': 32, 'lr': 0.00806827864310577}. Best is trial 46 with value: 0.8720903396606445.
[I 2026-03-24 13:02:30,240] Trial 49 finished with value: 0.8584104776382446 and parameters: {'n_layers': 1, 'n_units_l0': 16, 'lr': 0.004769379801457981}. Best is trial 46 with value: 0.8720903396606445.
[I 2026-03-24 13:02:30,393] Trial 50 finished with value: 0.8608519434928894 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.006932299204771953}. Best is trial 46 with value: 0.8720903396606445.
[I 2026-03-24 13:02:30,536] Trial 51 finished with value: 0.8506577014923096 and parameters: {'n_layers': 1, 'n_units_l0': 32, 'lr': 0.005947581118938077}. Best is trial 46 with value: 0.8720903396606445.
[I 2026-03-24 13:02:30,731] Trial 52 finished with value: 0.8558932542800903 and parameters: {'n_layers': 1, 'n_units_l0': 32, 'lr': 0.004340429392457641}. Best is trial 46 with value: 0.8720903396606445.
[I 2026-03-24 13:02:30,889] Trial 53 finished with value: 0.8682205677032471 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.0034993894904183937}. Best is trial 46 with value: 0.8720903396606445.
[I 2026-03-24 13:02:31,072] Trial 54 finished with value: 0.8641728162765503 and parameters: {'n_layers': 1, 'n_units_l0': 32, 'lr': 0.008851481421903267}. Best is trial 46 with value: 0.8720903396606445.
[I 2026-03-24 13:02:31,251] Trial 55 finished with value: 0.8505470752716064 and parameters: {'n_layers': 1, 'n_units_l0': 16, 'lr': 0.006561676189552302}. Best is trial 46 with value: 0.8720903396606445.
[I 2026-03-24 13:02:31,397] Trial 56 finished with value: 0.8265590071678162 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.0020072397697989994}. Best is trial 46 with value: 0.8720903396606445.
[I 2026-03-24 13:02:31,597] Trial 57 finished with value: 0.8634851574897766 and parameters: {'n_layers': 1, 'n_units_l0': 32, 'lr': 0.0052222223312875125}. Best is trial 46 with value: 0.8720903396606445.
[I 2026-03-24 13:02:31,717] Trial 58 finished with value: 0.8707013130187988 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.009901726886444518}. Best is trial 46 with value: 0.8720903396606445.
[I 2026-03-24 13:02:31,900] Trial 59 finished with value: 0.8753255605697632 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.009828852133168387}. Best is trial 59 with value: 0.8753255605697632.
[I 2026-03-24 13:02:32,131] Trial 60 finished with value: 0.8387114405632019 and parameters: {'n_layers': 2, 'n_units_l0': 48, 'n_units_l1': 112, 'lr': 0.00982426871104821}. Best is trial 59 with value: 0.8753255605697632.
[I 2026-03-24 13:02:32,289] Trial 61 finished with value: 0.86882084608078 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.008164104977543291}. Best is trial 59 with value: 0.8753255605697632.
[I 2026-03-24 13:02:32,468] Trial 62 finished with value: 0.8687147498130798 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.00809625009209955}. Best is trial 59 with value: 0.8753255605697632.
[I 2026-03-24 13:02:32,641] Trial 63 finished with value: 0.8624911308288574 and parameters: {'n_layers': 1, 'n_units_l0': 64, 'lr': 0.008177812639726974}. Best is trial 59 with value: 0.8753255605697632.
[I 2026-03-24 13:02:32,763] Trial 64 finished with value: 0.8616390228271484 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.006628243412816189}. Best is trial 59 with value: 0.8753255605697632.
[I 2026-03-24 13:02:32,934] Trial 65 finished with value: 0.873522162437439 and parameters: {'n_layers': 1, 'n_units_l0': 64, 'lr': 0.008630183436555002}. Best is trial 59 with value: 0.8753255605697632.
[I 2026-03-24 13:02:33,087] Trial 66 finished with value: 0.8754743933677673 and parameters: {'n_layers': 1, 'n_units_l0': 64, 'lr': 0.008633214952075016}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:33,215] Trial 67 finished with value: 0.8685479164123535 and parameters: {'n_layers': 1, 'n_units_l0': 64, 'lr': 0.009779984847584142}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:33,358] Trial 68 finished with value: 0.8590318560600281 and parameters: {'n_layers': 1, 'n_units_l0': 80, 'lr': 0.008539479574551959}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:33,482] Trial 69 finished with value: 0.8661366105079651 and parameters: {'n_layers': 1, 'n_units_l0': 64, 'lr': 0.00706212032776728}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:33,627] Trial 70 finished with value: 0.8700629472732544 and parameters: {'n_layers': 1, 'n_units_l0': 80, 'lr': 0.006283308755063361}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:33,757] Trial 71 finished with value: 0.8643435835838318 and parameters: {'n_layers': 1, 'n_units_l0': 80, 'lr': 0.0099282201303472}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:33,956] Trial 72 finished with value: 0.8664191961288452 and parameters: {'n_layers': 1, 'n_units_l0': 80, 'lr': 0.0061742376908743785}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:34,081] Trial 73 finished with value: 0.8679863214492798 and parameters: {'n_layers': 1, 'n_units_l0': 64, 'lr': 0.008884300870625528}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:34,247] Trial 74 finished with value: 0.8693176507949829 and parameters: {'n_layers': 1, 'n_units_l0': 96, 'lr': 0.004055636320409223}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:34,417] Trial 75 finished with value: 0.8574938774108887 and parameters: {'n_layers': 1, 'n_units_l0': 80, 'lr': 0.0066935091037728265}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:34,562] Trial 76 finished with value: 0.864747166633606 and parameters: {'n_layers': 1, 'n_units_l0': 64, 'lr': 0.005374544544093234}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:34,909] Trial 77 finished with value: 0.8340795040130615 and parameters: {'n_layers': 3, 'n_units_l0': 64, 'n_units_l1': 112, 'n_units_l2': 48, 'lr': 0.0032381048947545065}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:35,095] Trial 78 finished with value: 0.8579608798027039 and parameters: {'n_layers': 1, 'n_units_l0': 96, 'lr': 0.00780059910435705}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:35,270] Trial 79 finished with value: 0.6998436450958252 and parameters: {'n_layers': 1, 'n_units_l0': 64, 'lr': 0.0009057519213342105}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:35,421] Trial 80 finished with value: 0.47111475467681885 and parameters: {'n_layers': 1, 'n_units_l0': 80, 'lr': 0.0003356301915938096}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:35,540] Trial 81 finished with value: 0.8661414384841919 and parameters: {'n_layers': 1, 'n_units_l0': 96, 'lr': 0.004203969273559904}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:35,714] Trial 82 finished with value: 0.8650287389755249 and parameters: {'n_layers': 1, 'n_units_l0': 112, 'lr': 0.008705949952329824}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:35,856] Trial 83 finished with value: 0.8602703809738159 and parameters: {'n_layers': 1, 'n_units_l0': 112, 'lr': 0.006102471355362555}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:36,015] Trial 84 finished with value: 0.8688377141952515 and parameters: {'n_layers': 1, 'n_units_l0': 96, 'lr': 0.007475833893474369}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:36,162] Trial 85 finished with value: 0.5740871429443359 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.0005911377998809047}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:36,327] Trial 86 finished with value: 0.8527045249938965 and parameters: {'n_layers': 1, 'n_units_l0': 96, 'lr': 0.005203060582589678}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:36,490] Trial 87 finished with value: 0.864479660987854 and parameters: {'n_layers': 1, 'n_units_l0': 128, 'lr': 0.0023373832072606997}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:36,673] Trial 88 finished with value: 0.8691779375076294 and parameters: {'n_layers': 1, 'n_units_l0': 48, 'lr': 0.004011746945194232}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:36,852] Trial 89 finished with value: 0.8660277724266052 and parameters: {'n_layers': 1, 'n_units_l0': 80, 'lr': 0.007021229577350726}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:37,010] Trial 90 finished with value: 0.8703600168228149 and parameters: {'n_layers': 1, 'n_units_l0': 112, 'lr': 0.009011762654801542}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:37,150] Trial 91 finished with value: 0.8527637720108032 and parameters: {'n_layers': 1, 'n_units_l0': 112, 'lr': 0.008767886354695003}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:37,323] Trial 92 finished with value: 0.8685850501060486 and parameters: {'n_layers': 1, 'n_units_l0': 112, 'lr': 0.005791067336254163}. Best is trial 66 with value: 0.8754743933677673.
[I 2026-03-24 13:02:37,522] Trial 93 finished with value: 0.8617016077041626 and parameters: {'n_layers': 1, 'n_units_l0': 128, 'lr': 0.009888536738254709}. Best is trial 66 with value: 0.8754743933677673.

==============================
EL MEJOR VALOR DIRECTO: 0.8755
==============================
Configuración ganadora:
 -> n_layers: 1
 -> n_units_l0: 64
 -> lr: 0.008633214952075016